# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
#org.gradle.debug=false
mappingsVersion = 2023.08.13-1.20.1
modMixinVersion = 0.8.5
mappingsChannel = parchment
modGroup = com.stereowalker.actualfishing

## Publishing Porperties
_curseforge_id = 1062668
_modrinth_id   = Y1t4glur
## Environment Properties
_minecraft_version     = 1.20.1
_minecraft_version_min = 1.20
_minecraft_version_max = 1.21
_loader                = Forge
_loader_file           = META-INF/mods.toml
_loader_version        = 47.4.0
_loader_version_min    = 46
_loader_version_max    = 48
_unionlib_version      = 12.0.18
_unionlib_version_min  = 12.0.18
_unionlib_version_max  = 12.1.0
## Mod Properties
_mod_name          = Antique Atlas
_mod_id            = navigate
_mod_version       = 8.0.1
_mod_release       = release
_mod_environment   = client & server
_mod_license       = GNU GENERAL PUBLIC LICENSE
_mod_authors       = Hunternif, tyra314
_mod_issue_tracker = https://github.com/AntiqueAtlasTeam/AntiqueAtlas/issues
_mod_page          = https://www.curseforge.com/minecraft/mc-mods/antique-atlas
_mod_description   = Antique Atlas is a book that acts like a map featuring infinite scrolling, zoom and custom labeled markers. The map is generated around the player by calculating the average biome in each 16x16 chunk.
##Misc Properties
